# Generated by Django 5.2.1 on 2025-05-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="Ім'я студента")),
                ('student_class', models.CharField(max_length=100, verbose_name='Клас')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, verbose_name="Ім'я вчителя")),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
            ],
        ),
    ]
